from typing import Optional, Sequence

from ..interfaces import (ContactTracer, LocationID, NoOP, PandemicRegulation,
                          Person, PersonID, PersonState, SimTime)

class BasePerson(Person):
    def __init__(
        self,
        person_id: PersonID,
        home: LocationID,
        regulation_compliance_prob: float = ...,
        init_state: Optional[PersonState] = ...,
    ) -> None: ...
    def enter_location(self, location_id: LocationID) -> bool: ...
    @property
    def id(self) -> PersonID: ...
    @property
    def state(self) -> PersonState: ...
    @property
    def home(self) -> LocationID: ...
    @property
    def at_home(self) -> bool: ...
    @property
    def assigned_locations(self) -> Sequence[LocationID]: ...
    def step(
        self, sim_time: SimTime, contact_tracer: Optional[ContactTracer] = ...
    ) -> Optional[NoOP]: ...
    def receive_regulation(self, regulation: PandemicRegulation) -> None: ...
    def get_social_gathering_location(self) -> Optional[LocationID]: ...
    def reset(self) -> None: ...
