from ..environment import Location, LocationID, Person, PersonRoutine, PersonRoutineAssignment
from typing import Sequence, Type

class DefaultPersonRoutineAssignment(PersonRoutineAssignment):
    @property
    def required_location_types(self) -> Sequence[Type[Location]]: ...
    @staticmethod
    def get_minor_routines(home_id: LocationID, age: int) -> Sequence[PersonRoutine]: ...
    @staticmethod
    def get_retired_routines(home_id: LocationID) -> Sequence[PersonRoutine]: ...
    @staticmethod
    def get_worker_during_work_routines(work_id: LocationID) -> Sequence[PersonRoutine]: ...
    @staticmethod
    def get_worker_outside_work_routines(home_id: LocationID) -> Sequence[PersonRoutine]: ...
    def assign_routines(self, persons: Sequence[Person]) -> None: ...
