from typing import Mapping

import numpy as np
from ordered_set import OrderedSet

from ..interfaces import ContactTracer, PersonID

class MaxSlotContactTracer(ContactTracer):
    def __init__(
        self, storage_slots: int = ..., time_slot_scale: int = ...
    ) -> None: ...
    def new_time_slot(self) -> None: ...
    def reset(self) -> None: ...
    def add_contacts(self, contacts: OrderedSet) -> None: ...
    def get_contacts(self, person_id: PersonID) -> Mapping[PersonID, np.ndarray]: ...
